# Generated by Django 5.2 on 2025-11-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel_data', '0034_fix_credits_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='last_credit_deducted',
            field=models.DateField(blank=True, help_text='Date when the last credit was deducted (IST)', null=True),
        ),
        migrations.AlterField(
            model_name='chartaggregateddata',
            name='gross_salary',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='chartaggregateddata',
            name='net_payable',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salarydata',
            name='charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='LATE CHARGE'),
        ),
        migrations.AlterField(
            model_name='salarydata',
            name='charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='OT CHARGES'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the tenant is active (has credits > 0 and is not manually deactivated)'),
        ),
    ]
